import "./globals.css";
import { Inter, Space_Grotesk, Poppins } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const spaceGrotesk = Space_Grotesk({ subsets: ["latin"], variable: "--font-space" });
const poppins = Poppins({ subsets: ["latin"], weight: ["600","700"], variable: "--font-logo" });



export const metadata = {
  title: "DeveloperHub Agency platform",
  description: "Generated by Huraira Arshad",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${spaceGrotesk.variable} ${poppins.variable} h-full`}
    >
      <body >
          {children}
      </body>
    </html>
  );
}
