'use client'

import { useRouter } from 'next/navigation'
import { useEffect, useState } from 'react'

import Sidebar from '@/components/admin/Sidebar'
import Topbar from '@/components/admin/Topbar'

// metadate should be same for all admin pages to avoid confusion and for better SEO
// it giving error, i don't know why, so commenting it out for now, will fix it later
// export const metadata = {
//   title: 'Admin - DevelopersHub',
//   description: 'Generated by Huraira Arshad'
// }

export default function AdminLayout ({ children }) {
  const [loading, setLoading] = useState(true)


  const router = useRouter()

  useEffect(() => {
    const token = localStorage.getItem('token')

    if (!token) {
      router.push('/admin/login')
    } else{
      setLoading(false)
    }
  }, [router])
 if (loading) return <p>Checking authentication...</p>;
  return (
    <div className='flex min-h-screen'>
      {/* Sidebar */}
      <Sidebar />
      {/* Right Section */}
      <div className='flex-1 flex flex-col'>
        {/* Topbar */}
        <Topbar />
        {/* Page Content */}
        <main className='p-6 bg-gray-100 flex-1'>{children}</main>
      </div>
    </div>
  )
}
