import Sidebar from "@/components/admin/Sidebar";
import Topbar from "@/components/admin/Topbar";



export const metadata = {
  title: "Admin - DevelopersHub",
  description: "Generated by Huraira Arshad",
};

export default function AdminLayout({ children }) {

  return (
    





    <div className="flex min-h-screen">

      {/* Sidebar */}
      <Sidebar />

      {/* Right Section */}
      <div className="flex-1 flex flex-col">

        {/* Topbar */}
        <Topbar />

        {/* Page Content */}
        <main className="p-6 bg-gray-100 flex-1">
          {children}
        </main>

      </div>
    </div>
  );
}